name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13.1
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.1
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  lint:
    name: Lint

    needs: build

    runs-on: ubuntu-latest

    steps:
    - run: npm run lint

  test:
    name: Test

    needs: build

    runs-on: ubuntu-latest

    steps:
    - run: npm run test
